apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: llm-container
          image: 129.80.55.216:5000/my-llm:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
              nvidia.com/gpu: 1
