{{- if or (has "all" $.Values.provision) (has "cart-redis" $.Values.provision)}}
{{- range $namespace := $.Values.namespace }}
{{- range $copy := untilStep 0 ($.Values.copies | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: cart-redis-{{$copy}}
  namespace: {{ $namespace.config.name }}
  labels:
    app: acmefit
    service: cart-redis-{{$copy}}
spec:
  ports:
    - port: 6379
      name: redis-cart
  selector:
    app: acmefit
    service: cart-redis-{{$copy}}
---
apiVersion: apps/v1
{{- if $.Values.stateful}}
kind: StatefulSet
  {{- else }}
kind: Deployment
  {{- end }}
metadata:
  name: cart-redis-{{ $namespace.config.name }}-{{$copy}}
  namespace: {{ $namespace.config.name }}
  labels:
    app: acmefit
    service: cart-redis-{{$copy}}
    version: 1.0.0
spec:
  serviceName: cart-redis-{{$copy}}
  selector:
    matchLabels:
      app: acmefit  # has to match .spec.template.metadata.labels
      service: cart-redis-{{$copy}}
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit  # has to match .spec.selector.matchLabels
        service: cart-redis-{{$copy}}
    spec:
      containers:
        - name: cart-redis
          image: bitnami/redis
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
          env:
            - name: REDIS_HOST
              value: cart-redis-{{$copy}}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cart-redis-pass
                  key: password
          volumeMounts:
            - mountPath: /var/lib/redis
              name: cart-redis-data
      #            - mountPath: /etc/redis
      #              name: redis-config
      volumes:
        - name: cart-redis-data
          emptyDir: {}
      #        - name: redis-config
      #          configMap:
      #            name: redis-config
      #            items:
      #              - key: redis-config
      #                path: redis.conf
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-redis-{{$copy}}
  namespace: {{ $namespace.config.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-redis-{{ $namespace.config.name }}-{{$copy}}
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
---
{{- end }}
{{- end }}
{{- end }}