apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models-pvc
  namespace: raj
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-output-pvc
  namespace: raj
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
