{{- if or (has "all" $.Values.provision) (has "cart" $.Values.provision)}}
{{- range $namespace := $.Values.namespace }}
{{- range $copy := untilStep 0 ($.Values.copies | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: cart-{{$copy}}
  namespace: {{ $namespace.config.name }}
  labels:
    app: acmefit
    service: cart-{{$copy}}
spec:
  ports:
    - name: http-cart
      protocol: TCP
      port: 5000
  selector:
    app: acmefit
    service: cart-{{$copy}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-{{ $namespace.config.name }}-{{$copy}}
  namespace: {{ $namespace.config.name }}
  labels:
    app: acmefit
    service: cart-{{$copy}}
spec:
  selector:
    matchLabels:
      app: acmefit
      service: cart-{{$copy}}
    {{- if not $.Values.stateful}}
  strategy:
    type: Recreate
    {{- end}}
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: cart-{{$copy}}
    spec:
      volumes:
        - name: acmefit-cart-data
          emptyDir: { }
      containers:
        - image: gcr.io/vmwarecloudadvocacy/acmeshop-cart:latest
          imagePullPolicy: "Always"
          name: cart
          env:
            - name: REDIS_HOST
              value: cart-redis-{{$copy}}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cart-redis-pass
                  key: password
            - name: REDIS_PORT
              value: '6379'
            - name: CART_PORT
              value: '5000'
            - name: USER_HOST
              value: users-{{$copy}}
            - name: USER_PORT
              value: '8083'
            - name: JAEGER_AGENT_HOST
              value: 'localhost'
            - name: JAEGER_AGENT_PORT
              value: '6831'
            - name: AUTH_MODE
              value: '1'
          ports:
            - containerPort: 5000
              name: cart
          volumeMounts:
            - mountPath: "/data"
              name: "acmefit-cart-data"
          resources:
            requests:
              memory: "100Mi"
              cpu: "300m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-{{$copy}}
  namespace: {{ $namespace.config.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-{{ $namespace.config.name }}-{{$copy}}
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
---
{{- end }}
{{- end }}
{{- end }}