{{- if or (has "all" $.Values.provision) (has "payment-total" $.Values.provision)}}
{{- range $namespace := $.Values.namespace }}
  {{- range $copy := untilStep 0 ($.Values.copies | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-{{$copy}}
  namespace: {{ $namespace.config.name }}
  labels:
    app: acmefit
    service: payment-{{$copy}}
spec:
  ports:
    - name: http-payment
      protocol: TCP
      port: 9000
  selector:
    app: acmefit
    service: payment-{{$copy}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-{{ $namespace.config.name }}-{{$copy}}
  namespace: {{ $namespace.config.name }}
  labels:
    app: acmefit
    service: payment-{{$copy}}
spec:
  selector:
    matchLabels:
      app: acmefit
      service: payment-{{$copy}}
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: payment-{{$copy}}
    spec:
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-payment:latest
        name: payment
        resources:
          requests:
            cpu: "100m"
            memory: "350Mi"  
        env:
        - name: PAYMENT_PORT
          value: '9000'
        - name: USERS_HOST
          value: users-{{$copy}}
        - name: USERS_PORT
          value: '8083'
        - name: JAEGER_AGENT_HOST
          value: 'localhost'
        - name: JAEGER_AGENT_PORT
          value: '6832'
        ports:
        - containerPort: 9000
          name: payment
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-{{$copy}}
  namespace: {{ $namespace.config.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-{{ $namespace.config.name }}-{{$copy}}
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
---
{{- end }}
{{- end }}
{{- end }}