{{- range $namespace := $.Values.namespace }}
  {{- if or (has "all" $.Values.provision) (has "cart-redis" $.Values.provision)}}
---
apiVersion: v1
data:
  password: Q2FydA==
kind: Secret
metadata:
  name: cart-redis-pass
  namespace: {{ $namespace.config.name}}
type: Opaque
  {{- end }}
  {{- if or (has "all" $.Values.provision) (has "catalog-db-total" $.Values.provision)}}
---
apiVersion: v1
data:
  password: Y2F0YWxvZw==
kind: Secret
metadata:
  name: catalog-mongo-pass
  namespace: {{ $namespace.config.name}}
type: Opaque
{{- end }}
  {{- if or (has "all" $.Values.provision) (has "order-db-total" $.Values.provision)}}
---
apiVersion: v1
data:
  password: T3JkZXI=
kind: Secret
metadata:
  name: order-postgres-pass
  namespace: {{ $namespace.config.name}}
type: Opaque
{{- end }}
  {{- if or (has "all" $.Values.provision) (has "users-db-total" $.Values.provision)}}
---
apiVersion: v1
data:
  password: VXNlcnMtbW9uZ28=
kind: Secret
metadata:
  name: users-mongo-pass
  namespace: {{ $namespace.config.name}}
type: Opaque
{{- end }}
  {{- if or (has "all" $.Values.provision) (has "users-db-total" $.Values.provision)}}
---
apiVersion: v1
data:
  password: VXNlcnMtcmVkaXM=
kind: Secret
metadata:
  name: users-redis-pass
  namespace: {{ $namespace.config.name}}
type: Opaque
{{- end }}
---
{{- end}}