{{- if or (has "all" $.Values.provision) (has "cart" $.Values.provision)}}
{{- range $namespace := $.Values.namespace }}
{{- range $copy := untilStep 0 ($.Values.copies | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: users-{{$copy}}
  namespace: {{ $namespace.config.name }}
  labels:
    app: acmefit
    service: users-{{$copy}}
spec:
  ports:
    - name: http-users
      protocol: TCP
      port: 8083
  selector:
    app: acmefit
    service: users-{{$copy}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-{{ $namespace.config.name }}-{{$copy}}
  namespace: {{ $namespace.config.name }}
  labels:
    app: acmefit
    service: users-{{$copy}}
spec:
  selector:
    matchLabels:
      app: acmefit
      service: users-{{$copy}}
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: users-{{$copy}}
    spec:
      volumes:
      - name: acmefit-users-data
        emptyDir: {}
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-user:latest
        imagePullPolicy: "Always"
        name: users
        env:
        - name: USERS_DB_HOST
          value: users-mongo-{{$copy}}
        - name: USERS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-mongo-pass
              key: password
        - name: USERS_DB_PORT
          value: '27017'
        - name: USERS_DB_USERNAME
          value: mongoadmin
        - name: USERS_PORT
          value: '8083'
        - name: REDIS_HOST
          value: users-redis-{{$copy}}
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-redis-pass
              key: password
        - name: JAEGER_AGENT_HOST
          value: 'localhost'
        - name: JAEGER_AGENT_PORT
          value: '6831'
        ports:
        - containerPort: 8083
          name: users
        volumeMounts:
        - mountPath: "/data"
          name: "acmefit-users-data"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
{{- end }}
{{- end }}
{{- end }}